---
apiVersion: v1
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJyZWdpc3RyeS5saW54bGFicy5jb206NTAwMCI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiWVdSdGFXNDZjR0Z6YzNkdmNtUT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: sa-go-frontend
  labels:
    app: sa
    role: frontend
    env: production
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    run: sa-go-frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sa
    role: frontend
    env: production
  name: sa-go-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      labels:
        app: sa
        role: frontend
        run: sa-go-frontend
        env: production
    spec:
      containers:
      - image: SA_FRONTEND_CONTAINER_IMAGE
        name: sa-go-frontend
        ports:
        - containerPort: 8090
      imagePullSecrets:
      - name: regcred
